# Form implementation generated from reading ui file 'Admin.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 776)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setTabletTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1241, 121))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(635, 8, 101, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Untitled design (2).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(515, 34, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(745, 34, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_4.setObjectName("label_4")
        self.menuFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.menuFrame.setGeometry(QtCore.QRect(0, 0, 131, 781))
        self.menuFrame.setStyleSheet("QFrame#menuFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius:20px;\n"
"    background-color: rgb(65, 35, 127);\n"
"}\n"
"\n"
"\n"
"")
        self.menuFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.menuEmployeeFrame = QtWidgets.QFrame(parent=self.menuFrame)
        self.menuEmployeeFrame.setGeometry(QtCore.QRect(0, 0, 131, 161))
        self.menuEmployeeFrame.setStyleSheet("QFrame#menuEmployeeFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 20px;\n"
"    \n"
"    background-color: rgb(44, 10, 113);\n"
"}")
        self.menuEmployeeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuEmployeeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuEmployeeFrame.setObjectName("menuEmployeeFrame")
        self.personIcon = QtWidgets.QLabel(parent=self.menuEmployeeFrame)
        self.personIcon.setGeometry(QtCore.QRect(20, 10, 91, 91))
        self.personIcon.setText("")
        self.personIcon.setPixmap(QtGui.QPixmap("person icon.png"))
        self.personIcon.setScaledContents(True)
        self.personIcon.setObjectName("personIcon")
        self.label_3 = QtWidgets.QLabel(parent=self.menuEmployeeFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.menuLogoutFrame = QtWidgets.QFrame(parent=self.menuFrame)
        self.menuLogoutFrame.setGeometry(QtCore.QRect(0, 730, 131, 51))
        self.menuLogoutFrame.setStyleSheet("QFrame#menuLogoutFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 20px;\n"
"    \n"
"    background-color: rgb(44, 10, 113);\n"
"}")
        self.menuLogoutFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuLogoutFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuLogoutFrame.setObjectName("menuLogoutFrame")
        self.logoutButton = QtWidgets.QPushButton(parent=self.menuLogoutFrame)
        self.logoutButton.setGeometry(QtCore.QRect(10, 10, 101, 24))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding-left: 12px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logoutButton.setIcon(icon)
        self.logoutButton.setIconSize(QtCore.QSize(24, 24))
        self.logoutButton.setCheckable(False)
        self.logoutButton.setObjectName("logoutButton")
        self.recordsButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.recordsButton.setGeometry(QtCore.QRect(0, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.recordsButton.setFont(font)
        self.recordsButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("paper white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.recordsButton.setIcon(icon1)
        self.recordsButton.setIconSize(QtCore.QSize(30, 30))
        self.recordsButton.setCheckable(False)
        self.recordsButton.setObjectName("recordsButton")
        self.inventoryButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.inventoryButton.setGeometry(QtCore.QRect(0, 240, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.inventoryButton.setFont(font)
        self.inventoryButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("box.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.inventoryButton.setIcon(icon2)
        self.inventoryButton.setIconSize(QtCore.QSize(30, 30))
        self.inventoryButton.setCheckable(False)
        self.inventoryButton.setObjectName("inventoryButton")
        self.requestsButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.requestsButton.setGeometry(QtCore.QRect(0, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.requestsButton.setFont(font)
        self.requestsButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("mail.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.requestsButton.setIcon(icon3)
        self.requestsButton.setIconSize(QtCore.QSize(30, 30))
        self.requestsButton.setCheckable(False)
        self.requestsButton.setObjectName("requestsButton")
        self.inventoryButton_2 = QtWidgets.QPushButton(parent=self.menuFrame)
        self.inventoryButton_2.setGeometry(QtCore.QRect(0, 200, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.inventoryButton_2.setFont(font)
        self.inventoryButton_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("PC white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.inventoryButton_2.setIcon(icon4)
        self.inventoryButton_2.setIconSize(QtCore.QSize(30, 30))
        self.inventoryButton_2.setCheckable(False)
        self.inventoryButton_2.setObjectName("inventoryButton_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(130, 120, 1111, 661))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.setupFrame = QtWidgets.QWidget()
        self.setupFrame.setObjectName("setupFrame")
        self.label_6 = QtWidgets.QLabel(parent=self.setupFrame)
        self.label_6.setGeometry(QtCore.QRect(660, 240, 49, 16))
        self.label_6.setObjectName("label_6")
        self.setupTableWidget = QtWidgets.QTableWidget(parent=self.setupFrame)
        self.setupTableWidget.setGeometry(QtCore.QRect(100, 76, 911, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupTableWidget.sizePolicy().hasHeightForWidth())
        self.setupTableWidget.setSizePolicy(sizePolicy)
        self.setupTableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.setupTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.setupTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.setupTableWidget.setObjectName("setupTableWidget")
        self.setupTableWidget.setColumnCount(4)
        self.setupTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        item.setFont(font)
        self.setupTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.setupTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.setupTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.setupTableWidget.setHorizontalHeaderItem(3, item)
        self.setupTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.setupTableWidget.horizontalHeader().setDefaultSectionSize(227)
        self.setupTableWidget.horizontalHeader().setStretchLastSection(True)
        self.setupTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.setupTableWidget.verticalHeader().setStretchLastSection(False)
        self.label_5 = QtWidgets.QLabel(parent=self.setupFrame)
        self.label_5.setGeometry(QtCore.QRect(395, 16, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.setupFrame)
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.rframe1 = QtWidgets.QFrame(parent=self.dashboard)
        self.rframe1.setGeometry(QtCore.QRect(265, 18, 151, 111))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.rframe1.setFont(font)
        self.rframe1.setStyleSheet("QFrame#rframe1 {\n"
" border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"}")
        self.rframe1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rframe1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rframe1.setObjectName("rframe1")
        self.label_9 = QtWidgets.QLabel(parent=self.rframe1)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.r1No = QtWidgets.QLabel(parent=self.rframe1)
        self.r1No.setGeometry(QtCore.QRect(100, 40, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        self.r1No.setFont(font)
        self.r1No.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.r1No.setObjectName("r1No")
        self.rframe2 = QtWidgets.QFrame(parent=self.dashboard)
        self.rframe2.setGeometry(QtCore.QRect(480, 20, 151, 111))
        self.rframe2.setStyleSheet("QFrame#rframe2 {\n"
" border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"}")
        self.rframe2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rframe2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rframe2.setObjectName("rframe2")
        self.r2No = QtWidgets.QLabel(parent=self.rframe2)
        self.r2No.setGeometry(QtCore.QRect(35, 40, 96, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        self.r2No.setFont(font)
        self.r2No.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.r2No.setObjectName("r2No")
        self.label_10 = QtWidgets.QLabel(parent=self.rframe2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.rframe4 = QtWidgets.QFrame(parent=self.dashboard)
        self.rframe4.setGeometry(QtCore.QRect(695, 22, 151, 111))
        self.rframe4.setStyleSheet("QFrame#rframe4 {\n"
" border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"}")
        self.rframe4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rframe4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rframe4.setObjectName("rframe4")
        self.label_12 = QtWidgets.QLabel(parent=self.rframe4)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.r2No_3 = QtWidgets.QLabel(parent=self.rframe4)
        self.r2No_3.setGeometry(QtCore.QRect(100, 40, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        self.r2No_3.setFont(font)
        self.r2No_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.r2No_3.setObjectName("r2No_3")
        self.graphWidget = QtWidgets.QWidget(parent=self.dashboard)
        self.graphWidget.setGeometry(QtCore.QRect(100, 154, 891, 441))
        self.graphWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphWidget.setObjectName("graphWidget")
        self.stackedWidget.addWidget(self.dashboard)
        self.reqFrame = QtWidgets.QWidget()
        self.reqFrame.setObjectName("reqFrame")
        self.requesttableWidget = QtWidgets.QTableWidget(parent=self.reqFrame)
        self.requesttableWidget.setGeometry(QtCore.QRect(120, 62, 871, 223))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.requesttableWidget.setFont(font)
        self.requesttableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.requesttableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.requesttableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.requesttableWidget.setObjectName("requesttableWidget")
        self.requesttableWidget.setColumnCount(4)
        self.requesttableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.requesttableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.requesttableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.requesttableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.requesttableWidget.setHorizontalHeaderItem(3, item)
        self.requesttableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.requesttableWidget.horizontalHeader().setStretchLastSection(True)
        self.requesttableWidget.verticalHeader().setStretchLastSection(False)
        self.label_14 = QtWidgets.QLabel(parent=self.reqFrame)
        self.label_14.setGeometry(QtCore.QRect(120, 12, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_14.setObjectName("label_14")
        self.requestSelectButton = QtWidgets.QPushButton(parent=self.reqFrame)
        self.requestSelectButton.setGeometry(QtCore.QRect(505, 292, 106, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.requestSelectButton.setFont(font)
        self.requestSelectButton.setStyleSheet("background-color: rgb(65, 35, 127);\n"
"color: white;              \n"
" border-radius: 10px;    \n"
"")
        self.requestSelectButton.setObjectName("requestSelectButton")
        self.label_15 = QtWidgets.QLabel(parent=self.reqFrame)
        self.label_15.setGeometry(QtCore.QRect(50, 324, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_15.setObjectName("label_15")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.reqFrame)
        self.tableWidget.setGeometry(QtCore.QRect(50, 370, 1011, 211))
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(143)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(24)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.requestSelectButton_2 = QtWidgets.QPushButton(parent=self.reqFrame)
        self.requestSelectButton_2.setGeometry(QtCore.QRect(500, 588, 116, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.requestSelectButton_2.setFont(font)
        self.requestSelectButton_2.setStyleSheet("background-color: rgb(65, 35, 127);\n"
"color: white;              \n"
" border-radius: 10px;    \n"
"")
        self.requestSelectButton_2.setObjectName("requestSelectButton_2")
        self.stackedWidget.addWidget(self.reqFrame)
        self.invFrame = QtWidgets.QWidget()
        self.invFrame.setObjectName("invFrame")
        self.computertableWidget = QtWidgets.QTableWidget(parent=self.invFrame)
        self.computertableWidget.setGeometry(QtCore.QRect(75, 44, 951, 191))
        self.computertableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.computertableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.computertableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.computertableWidget.setObjectName("computertableWidget")
        self.computertableWidget.setColumnCount(3)
        self.computertableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.computertableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.computertableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.computertableWidget.setHorizontalHeaderItem(2, item)
        self.computertableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.computertableWidget.horizontalHeader().setStretchLastSection(True)
        self.computertableWidget.verticalHeader().setStretchLastSection(False)
        self.label_7 = QtWidgets.QLabel(parent=self.invFrame)
        self.label_7.setGeometry(QtCore.QRect(80, 0, 321, 49))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_7.setObjectName("label_7")
        self.hardwaretableWidget = QtWidgets.QTableWidget(parent=self.invFrame)
        self.hardwaretableWidget.setGeometry(QtCore.QRect(80, 340, 951, 261))
        self.hardwaretableWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.hardwaretableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.hardwaretableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.hardwaretableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.hardwaretableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.hardwaretableWidget.setAutoScroll(False)
        self.hardwaretableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.hardwaretableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.hardwaretableWidget.setObjectName("hardwaretableWidget")
        self.hardwaretableWidget.setColumnCount(3)
        self.hardwaretableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.hardwaretableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.hardwaretableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.hardwaretableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hardwaretableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwaretableWidget.setItem(4, 1, item)
        self.hardwaretableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.hardwaretableWidget.horizontalHeader().setDefaultSectionSize(280)
        self.hardwaretableWidget.horizontalHeader().setStretchLastSection(True)
        self.hardwaretableWidget.verticalHeader().setVisible(True)
        self.hardwaretableWidget.verticalHeader().setDefaultSectionSize(46)
        self.hardwaretableWidget.verticalHeader().setHighlightSections(True)
        self.hardwaretableWidget.verticalHeader().setSortIndicatorShown(False)
        self.hardwaretableWidget.verticalHeader().setStretchLastSection(True)
        self.label_13 = QtWidgets.QLabel(parent=self.invFrame)
        self.label_13.setGeometry(QtCore.QRect(80, 290, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_13.setObjectName("label_13")
        self.monitorAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.monitorAdd.setGeometry(QtCore.QRect(830, 378, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.monitorAdd.setFont(font)
        self.monitorAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.monitorAdd.setObjectName("monitorAdd")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.invFrame)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 378, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.kmAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.kmAdd.setGeometry(QtCore.QRect(830, 424, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.kmAdd.setFont(font)
        self.kmAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.kmAdd.setObjectName("kmAdd")
        self.gpuAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.gpuAdd.setGeometry(QtCore.QRect(830, 470, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.gpuAdd.setFont(font)
        self.gpuAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.gpuAdd.setObjectName("gpuAdd")
        self.motherboardAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.motherboardAdd.setGeometry(QtCore.QRect(830, 514, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.motherboardAdd.setFont(font)
        self.motherboardAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.motherboardAdd.setObjectName("motherboardAdd")
        self.ramAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.ramAdd.setGeometry(QtCore.QRect(830, 562, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.ramAdd.setFont(font)
        self.ramAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.ramAdd.setObjectName("ramAdd")
        self.kmSub = QtWidgets.QPushButton(parent=self.invFrame)
        self.kmSub.setGeometry(QtCore.QRect(900, 424, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.kmSub.setFont(font)
        self.kmSub.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.kmSub.setObjectName("kmSub")
        self.gpuSub = QtWidgets.QPushButton(parent=self.invFrame)
        self.gpuSub.setGeometry(QtCore.QRect(900, 470, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.gpuSub.setFont(font)
        self.gpuSub.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.gpuSub.setObjectName("gpuSub")
        self.motherboardSub = QtWidgets.QPushButton(parent=self.invFrame)
        self.motherboardSub.setGeometry(QtCore.QRect(900, 514, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.motherboardSub.setFont(font)
        self.motherboardSub.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.motherboardSub.setObjectName("motherboardSub")
        self.ramSub = QtWidgets.QPushButton(parent=self.invFrame)
        self.ramSub.setGeometry(QtCore.QRect(900, 562, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.ramSub.setFont(font)
        self.ramSub.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.ramSub.setObjectName("ramSub")
        self.requestSelectButton_3 = QtWidgets.QPushButton(parent=self.invFrame)
        self.requestSelectButton_3.setGeometry(QtCore.QRect(475, 244, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.requestSelectButton_3.setFont(font)
        self.requestSelectButton_3.setStyleSheet("background-color: rgb(65, 35, 127);\n"
"color: white;              \n"
" border-radius: 10px;    \n"
"")
        self.requestSelectButton_3.setObjectName("requestSelectButton_3")
        self.stackedWidget.addWidget(self.invFrame)
        self.frame.raise_()
        self.stackedWidget.raise_()
        self.menuFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "DAVAO"))
        self.label_4.setText(_translate("MainWindow", "BRANCH"))
        self.label_3.setText(_translate("MainWindow", "Manager: Name"))
        self.logoutButton.setText(_translate("MainWindow", "Log out"))
        self.recordsButton.setText(_translate("MainWindow", "Dashboard"))
        self.inventoryButton.setText(_translate("MainWindow", "Inventory"))
        self.requestsButton.setText(_translate("MainWindow", "Requests"))
        self.inventoryButton_2.setText(_translate("MainWindow", "Setups"))
        self.label_6.setText(_translate("MainWindow", "2"))
        item = self.setupTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Employee ID"))
        item = self.setupTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee Fullname"))
        item = self.setupTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pc Number"))
        item = self.setupTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date Acquired"))
        self.label_5.setText(_translate("MainWindow", "Current Arrangement"))
        self.label_9.setText(_translate("MainWindow", "Total Setup Active"))
        self.r1No.setText(_translate("MainWindow", "0"))
        self.r2No.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Total Items"))
        self.label_12.setText(_translate("MainWindow", "Available PCs"))
        self.r2No_3.setText(_translate("MainWindow", "0"))
        item = self.requesttableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PC No."))
        item = self.requesttableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee ID"))
        item = self.requesttableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Hardware Change"))
        item = self.requesttableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Reason"))
        self.label_14.setText(_translate("MainWindow", "Hardware Replacement Request"))
        self.requestSelectButton.setText(_translate("MainWindow", "Select Request"))
        self.label_15.setText(_translate("MainWindow", "Request Records"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PC No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Employee Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Request Change"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Action"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date Granted/Denied"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Validator"))
        self.requestSelectButton_2.setText(_translate("MainWindow", "Generate Report"))
        item = self.computertableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PC Number"))
        item = self.computertableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Assigned To"))
        item = self.computertableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        self.label_7.setText(_translate("MainWindow", "Computer Setups"))
        item = self.hardwaretableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Monitor"))
        item = self.hardwaretableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Keyboard & Mouse"))
        item = self.hardwaretableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "GPU"))
        item = self.hardwaretableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Motherboard"))
        item = self.hardwaretableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "RAM"))
        item = self.hardwaretableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Brand"))
        item = self.hardwaretableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.hardwaretableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Action"))
        __sortingEnabled = self.hardwaretableWidget.isSortingEnabled()
        self.hardwaretableWidget.setSortingEnabled(False)
        item = self.hardwaretableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Lenovo"))
        item = self.hardwaretableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.hardwaretableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Logitech"))
        item = self.hardwaretableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.hardwaretableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Nvidia"))
        item = self.hardwaretableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.hardwaretableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "ROG"))
        item = self.hardwaretableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.hardwaretableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Kingston"))
        item = self.hardwaretableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "0"))
        self.hardwaretableWidget.setSortingEnabled(__sortingEnabled)
        self.label_13.setText(_translate("MainWindow", "Hardware"))
        self.monitorAdd.setText(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.kmAdd.setText(_translate("MainWindow", "+"))
        self.gpuAdd.setText(_translate("MainWindow", "+"))
        self.motherboardAdd.setText(_translate("MainWindow", "+"))
        self.ramAdd.setText(_translate("MainWindow", "+"))
        self.kmSub.setText(_translate("MainWindow", "-"))
        self.gpuSub.setText(_translate("MainWindow", "-"))
        self.motherboardSub.setText(_translate("MainWindow", "-"))
        self.ramSub.setText(_translate("MainWindow", "-"))
        self.requestSelectButton_3.setText(_translate("MainWindow", "Create New Computer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
