# Form implementation generated from reading ui file 'Adminv8.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setTabletTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1101, 121))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(566, 12, 98, 98))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Untitled design (2).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(445, 30, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(670, 30, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_4.setObjectName("label_4")
        self.menuFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.menuFrame.setGeometry(QtCore.QRect(0, 0, 131, 703))
        self.menuFrame.setStyleSheet("QFrame#menuFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius:20px;\n"
"    background-color: rgb(65, 35, 127);\n"
"}\n"
"\n"
"\n"
"")
        self.menuFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.menuEmployeeFrame = QtWidgets.QFrame(parent=self.menuFrame)
        self.menuEmployeeFrame.setGeometry(QtCore.QRect(0, 0, 131, 161))
        self.menuEmployeeFrame.setStyleSheet("QFrame#menuEmployeeFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 20px;\n"
"    \n"
"    background-color: rgb(44, 10, 113);\n"
"}")
        self.menuEmployeeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuEmployeeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuEmployeeFrame.setObjectName("menuEmployeeFrame")
        self.personIcon = QtWidgets.QLabel(parent=self.menuEmployeeFrame)
        self.personIcon.setGeometry(QtCore.QRect(20, 10, 91, 91))
        self.personIcon.setText("")
        self.personIcon.setPixmap(QtGui.QPixmap("person icon.png"))
        self.personIcon.setScaledContents(True)
        self.personIcon.setObjectName("personIcon")
        self.label_3 = QtWidgets.QLabel(parent=self.menuEmployeeFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.menuLogoutFrame = QtWidgets.QFrame(parent=self.menuFrame)
        self.menuLogoutFrame.setGeometry(QtCore.QRect(0, 650, 131, 51))
        self.menuLogoutFrame.setStyleSheet("QFrame#menuLogoutFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 20px;\n"
"    \n"
"    background-color: rgb(44, 10, 113);\n"
"}")
        self.menuLogoutFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuLogoutFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuLogoutFrame.setObjectName("menuLogoutFrame")
        self.logoutButton = QtWidgets.QPushButton(parent=self.menuLogoutFrame)
        self.logoutButton.setGeometry(QtCore.QRect(10, 10, 101, 24))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding-left: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logoutButton.setIcon(icon)
        self.logoutButton.setIconSize(QtCore.QSize(24, 24))
        self.logoutButton.setCheckable(False)
        self.logoutButton.setObjectName("logoutButton")
        self.dashboardButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.dashboardButton.setGeometry(QtCore.QRect(0, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.dashboardButton.setFont(font)
        self.dashboardButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("paper white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.dashboardButton.setIcon(icon1)
        self.dashboardButton.setIconSize(QtCore.QSize(30, 30))
        self.dashboardButton.setCheckable(False)
        self.dashboardButton.setObjectName("dashboardButton")
        self.inventoryButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.inventoryButton.setGeometry(QtCore.QRect(0, 240, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.inventoryButton.setFont(font)
        self.inventoryButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("box.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.inventoryButton.setIcon(icon2)
        self.inventoryButton.setIconSize(QtCore.QSize(30, 30))
        self.inventoryButton.setCheckable(False)
        self.inventoryButton.setObjectName("inventoryButton")
        self.requestsButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.requestsButton.setGeometry(QtCore.QRect(0, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.requestsButton.setFont(font)
        self.requestsButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("mail.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.requestsButton.setIcon(icon3)
        self.requestsButton.setIconSize(QtCore.QSize(30, 30))
        self.requestsButton.setCheckable(False)
        self.requestsButton.setObjectName("requestsButton")
        self.setupsButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.setupsButton.setGeometry(QtCore.QRect(0, 200, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.setupsButton.setFont(font)
        self.setupsButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("PC white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.setupsButton.setIcon(icon4)
        self.setupsButton.setIconSize(QtCore.QSize(30, 30))
        self.setupsButton.setCheckable(False)
        self.setupsButton.setObjectName("setupsButton")
        self.registerButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.registerButton.setGeometry(QtCore.QRect(0, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../IT5 Program/Images/adduser.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.registerButton.setIcon(icon5)
        self.registerButton.setIconSize(QtCore.QSize(30, 30))
        self.registerButton.setCheckable(False)
        self.registerButton.setObjectName("registerButton")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(130, 120, 971, 639))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.setupFrame = QtWidgets.QWidget()
        self.setupFrame.setObjectName("setupFrame")
        self.label_6 = QtWidgets.QLabel(parent=self.setupFrame)
        self.label_6.setGeometry(QtCore.QRect(660, 240, 49, 16))
        self.label_6.setObjectName("label_6")
        self.assignedComputersTable = QtWidgets.QTableWidget(parent=self.setupFrame)
        self.assignedComputersTable.setGeometry(QtCore.QRect(30, 52, 911, 467))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assignedComputersTable.sizePolicy().hasHeightForWidth())
        self.assignedComputersTable.setSizePolicy(sizePolicy)
        self.assignedComputersTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.assignedComputersTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.assignedComputersTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.assignedComputersTable.setObjectName("assignedComputersTable")
        self.assignedComputersTable.setColumnCount(4)
        self.assignedComputersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        item.setFont(font)
        self.assignedComputersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.assignedComputersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.assignedComputersTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.assignedComputersTable.setHorizontalHeaderItem(3, item)
        self.assignedComputersTable.horizontalHeader().setCascadingSectionResizes(True)
        self.assignedComputersTable.horizontalHeader().setDefaultSectionSize(227)
        self.assignedComputersTable.horizontalHeader().setHighlightSections(False)
        self.assignedComputersTable.horizontalHeader().setStretchLastSection(True)
        self.assignedComputersTable.verticalHeader().setCascadingSectionResizes(True)
        self.assignedComputersTable.verticalHeader().setStretchLastSection(False)
        self.label_5 = QtWidgets.QLabel(parent=self.setupFrame)
        self.label_5.setGeometry(QtCore.QRect(330, 5, 306, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_5.setObjectName("label_5")
        self.removeButton = QtWidgets.QPushButton(parent=self.setupFrame)
        self.removeButton.setGeometry(QtCore.QRect(431, 530, 106, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.removeButton.setFont(font)
        self.removeButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.removeButton.setObjectName("removeButton")
        self.stackedWidget.addWidget(self.setupFrame)
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.rframe1 = QtWidgets.QFrame(parent=self.dashboard)
        self.rframe1.setGeometry(QtCore.QRect(195, 14, 151, 111))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.rframe1.setFont(font)
        self.rframe1.setStyleSheet("QFrame#rframe1 {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame#rframe1:hover {\n"
"    background-color: #E0E0E0;\n"
"}")
        self.rframe1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rframe1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rframe1.setObjectName("rframe1")
        self.label_9 = QtWidgets.QLabel(parent=self.rframe1)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.r1No = QtWidgets.QLabel(parent=self.rframe1)
        self.r1No.setGeometry(QtCore.QRect(100, 40, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        self.r1No.setFont(font)
        self.r1No.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.r1No.setObjectName("r1No")
        self.rframe2 = QtWidgets.QFrame(parent=self.dashboard)
        self.rframe2.setGeometry(QtCore.QRect(410, 16, 151, 111))
        self.rframe2.setStyleSheet("QFrame#rframe2 {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame#rframe2:hover {\n"
"    background-color: #E0E0E0;\n"
"}")
        self.rframe2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rframe2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rframe2.setObjectName("rframe2")
        self.r2No = QtWidgets.QLabel(parent=self.rframe2)
        self.r2No.setGeometry(QtCore.QRect(35, 40, 96, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        self.r2No.setFont(font)
        self.r2No.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.r2No.setObjectName("r2No")
        self.label_10 = QtWidgets.QLabel(parent=self.rframe2)
        self.label_10.setGeometry(QtCore.QRect(5, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(9)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.rframe4 = QtWidgets.QFrame(parent=self.dashboard)
        self.rframe4.setGeometry(QtCore.QRect(625, 14, 151, 111))
        self.rframe4.setStyleSheet("QFrame#rframe4 {\n"
"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame#rframe4:hover {\n"
"    background-color: #E0E0E0;\n"
"}")
        self.rframe4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rframe4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rframe4.setObjectName("rframe4")
        self.label_12 = QtWidgets.QLabel(parent=self.rframe4)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(9)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.r2No_3 = QtWidgets.QLabel(parent=self.rframe4)
        self.r2No_3.setGeometry(QtCore.QRect(100, 40, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        self.r2No_3.setFont(font)
        self.r2No_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.r2No_3.setObjectName("r2No_3")
        self.graphWidget = QtWidgets.QWidget(parent=self.dashboard)
        self.graphWidget.setGeometry(QtCore.QRect(105, 184, 761, 341))
        self.graphWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphWidget.setObjectName("graphWidget")
        self.label_8 = QtWidgets.QLabel(parent=self.dashboard)
        self.label_8.setGeometry(QtCore.QRect(115, 122, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(parent=self.dashboard)
        self.frame_2.setGeometry(QtCore.QRect(110, 540, 20, 20))
        self.frame_2.setStyleSheet("background-color: rgb(56, 142, 60);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.dashboard)
        self.frame_3.setGeometry(QtCore.QRect(400, 540, 20, 20))
        self.frame_3.setStyleSheet("background-color: rgb(251, 192, 45);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(parent=self.dashboard)
        self.frame_4.setGeometry(QtCore.QRect(660, 540, 20, 20))
        self.frame_4.setStyleSheet("background-color: rgb(211, 47, 47);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(parent=self.dashboard)
        self.label_11.setGeometry(QtCore.QRect(140, 540, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(parent=self.dashboard)
        self.label_16.setGeometry(QtCore.QRect(430, 540, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.dashboard)
        self.label_17.setGeometry(QtCore.QRect(690, 540, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.stackedWidget.addWidget(self.dashboard)
        self.registrationFrame = QtWidgets.QWidget()
        self.registrationFrame.setObjectName("registrationFrame")
        self.frame_5 = QtWidgets.QFrame(parent=self.registrationFrame)
        self.frame_5.setGeometry(QtCore.QRect(300, 50, 371, 476))
        self.frame_5.setStyleSheet("QFrame#frame_5 {\n"
"        background-color: white;\n"
"        border-radius: 15px; \n"
"    }")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(45, 15, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(20)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.FNInput = QtWidgets.QLineEdit(parent=self.frame_5)
        self.FNInput.setGeometry(QtCore.QRect(45, 134, 281, 31))
        self.FNInput.setStyleSheet("border: 1px solid black;")
        self.FNInput.setObjectName("FNInput")
        self.mnlabel = QtWidgets.QLabel(parent=self.frame_5)
        self.mnlabel.setGeometry(QtCore.QRect(45, 174, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        self.mnlabel.setFont(font)
        self.mnlabel.setObjectName("mnlabel")
        self.MNInput = QtWidgets.QLineEdit(parent=self.frame_5)
        self.MNInput.setGeometry(QtCore.QRect(45, 204, 281, 31))
        self.MNInput.setStyleSheet("border: 1px solid black;")
        self.MNInput.setObjectName("MNInput")
        self.lnlabel = QtWidgets.QLabel(parent=self.frame_5)
        self.lnlabel.setGeometry(QtCore.QRect(45, 244, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        self.lnlabel.setFont(font)
        self.lnlabel.setObjectName("lnlabel")
        self.LNInput = QtWidgets.QLineEdit(parent=self.frame_5)
        self.LNInput.setGeometry(QtCore.QRect(45, 274, 281, 31))
        self.LNInput.setStyleSheet("border: 1px solid black;")
        self.LNInput.setObjectName("LNInput")
        self.lnlabel_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.lnlabel_2.setGeometry(QtCore.QRect(45, 309, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        self.lnlabel_2.setFont(font)
        self.lnlabel_2.setObjectName("lnlabel_2")
        self.passRegInput = QtWidgets.QLineEdit(parent=self.frame_5)
        self.passRegInput.setGeometry(QtCore.QRect(45, 344, 281, 31))
        self.passRegInput.setStyleSheet("border: 1px solid black;")
        self.passRegInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passRegInput.setObjectName("passRegInput")
        self.signUpButton = QtWidgets.QPushButton(parent=self.frame_5)
        self.signUpButton.setGeometry(QtCore.QRect(45, 415, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.signUpButton.setFont(font)
        self.signUpButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.signUpButton.setObjectName("signUpButton")
        self.userLabel = QtWidgets.QLabel(parent=self.frame_5)
        self.userLabel.setGeometry(QtCore.QRect(45, 104, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        self.userLabel.setFont(font)
        self.userLabel.setObjectName("userLabel")
        self.userLabel_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.userLabel_2.setGeometry(QtCore.QRect(35, 60, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.userLabel_2.setFont(font)
        self.userLabel_2.setStyleSheet("color: rgb(83, 83, 83);")
        self.userLabel_2.setObjectName("userLabel_2")
        self.stackedWidget.addWidget(self.registrationFrame)
        self.reqFrame = QtWidgets.QWidget()
        self.reqFrame.setObjectName("reqFrame")
        self.issueReportsTable = QtWidgets.QTableWidget(parent=self.reqFrame)
        self.issueReportsTable.setGeometry(QtCore.QRect(50, 48, 871, 179))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.issueReportsTable.setFont(font)
        self.issueReportsTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.issueReportsTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.issueReportsTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.issueReportsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.issueReportsTable.setObjectName("issueReportsTable")
        self.issueReportsTable.setColumnCount(3)
        self.issueReportsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.issueReportsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.issueReportsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.issueReportsTable.setHorizontalHeaderItem(2, item)
        self.issueReportsTable.horizontalHeader().setVisible(True)
        self.issueReportsTable.horizontalHeader().setDefaultSectionSize(200)
        self.issueReportsTable.horizontalHeader().setHighlightSections(False)
        self.issueReportsTable.horizontalHeader().setStretchLastSection(True)
        self.issueReportsTable.verticalHeader().setHighlightSections(True)
        self.issueReportsTable.verticalHeader().setStretchLastSection(False)
        self.label_14 = QtWidgets.QLabel(parent=self.reqFrame)
        self.label_14.setGeometry(QtCore.QRect(60, 0, 466, 43))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_14.setObjectName("label_14")
        self.selectRequestButton = QtWidgets.QPushButton(parent=self.reqFrame)
        self.selectRequestButton.setGeometry(QtCore.QRect(425, 236, 116, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.selectRequestButton.setFont(font)
        self.selectRequestButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.selectRequestButton.setObjectName("selectRequestButton")
        self.label_15 = QtWidgets.QLabel(parent=self.reqFrame)
        self.label_15.setGeometry(QtCore.QRect(25, 264, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_15.setObjectName("label_15")
        self.requestReportsTable = QtWidgets.QTableWidget(parent=self.reqFrame)
        self.requestReportsTable.setGeometry(QtCore.QRect(15, 310, 941, 211))
        self.requestReportsTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.requestReportsTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.requestReportsTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.requestReportsTable.setObjectName("requestReportsTable")
        self.requestReportsTable.setColumnCount(8)
        self.requestReportsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.requestReportsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.requestReportsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.requestReportsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.requestReportsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.requestReportsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.requestReportsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.requestReportsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.requestReportsTable.setHorizontalHeaderItem(7, item)
        self.requestReportsTable.horizontalHeader().setDefaultSectionSize(153)
        self.requestReportsTable.horizontalHeader().setMinimumSectionSize(24)
        self.requestReportsTable.horizontalHeader().setStretchLastSection(True)
        self.requestReportsTable.verticalHeader().setDefaultSectionSize(30)
        self.requestReportsTable.verticalHeader().setMinimumSectionSize(24)
        self.requestReportsTable.verticalHeader().setStretchLastSection(False)
        self.generateReportButton = QtWidgets.QPushButton(parent=self.reqFrame)
        self.generateReportButton.setGeometry(QtCore.QRect(425, 530, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.generateReportButton.setFont(font)
        self.generateReportButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.generateReportButton.setObjectName("generateReportButton")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.reqFrame)
        self.dateEdit.setGeometry(QtCore.QRect(845, 280, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.showAllBox = QtWidgets.QCheckBox(parent=self.reqFrame)
        self.showAllBox.setGeometry(QtCore.QRect(766, 282, 76, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.showAllBox.setFont(font)
        self.showAllBox.setObjectName("showAllBox")
        self.stackedWidget.addWidget(self.reqFrame)
        self.invFrame = QtWidgets.QWidget()
        self.invFrame.setObjectName("invFrame")
        self.computerSetupsTable = QtWidgets.QTableWidget(parent=self.invFrame)
        self.computerSetupsTable.setGeometry(QtCore.QRect(10, 36, 951, 191))
        self.computerSetupsTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.computerSetupsTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.computerSetupsTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.computerSetupsTable.setObjectName("computerSetupsTable")
        self.computerSetupsTable.setColumnCount(3)
        self.computerSetupsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.computerSetupsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.computerSetupsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.computerSetupsTable.setHorizontalHeaderItem(2, item)
        self.computerSetupsTable.horizontalHeader().setDefaultSectionSize(300)
        self.computerSetupsTable.horizontalHeader().setStretchLastSection(True)
        self.computerSetupsTable.verticalHeader().setStretchLastSection(False)
        self.label_7 = QtWidgets.QLabel(parent=self.invFrame)
        self.label_7.setGeometry(QtCore.QRect(20, -2, 251, 37))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(22)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_7.setObjectName("label_7")
        self.hardwareTable = QtWidgets.QTableWidget(parent=self.invFrame)
        self.hardwareTable.setGeometry(QtCore.QRect(10, 297, 951, 236))
        self.hardwareTable.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.hardwareTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.hardwareTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.hardwareTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.hardwareTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.hardwareTable.setAutoScroll(False)
        self.hardwareTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.hardwareTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.hardwareTable.setObjectName("hardwareTable")
        self.hardwareTable.setColumnCount(3)
        self.hardwareTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.hardwareTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.hardwareTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.hardwareTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hardwareTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hardwareTable.setItem(4, 1, item)
        self.hardwareTable.horizontalHeader().setCascadingSectionResizes(False)
        self.hardwareTable.horizontalHeader().setDefaultSectionSize(279)
        self.hardwareTable.horizontalHeader().setHighlightSections(True)
        self.hardwareTable.horizontalHeader().setMinimumSectionSize(30)
        self.hardwareTable.horizontalHeader().setStretchLastSection(True)
        self.hardwareTable.verticalHeader().setVisible(True)
        self.hardwareTable.verticalHeader().setCascadingSectionResizes(False)
        self.hardwareTable.verticalHeader().setDefaultSectionSize(42)
        self.hardwareTable.verticalHeader().setHighlightSections(True)
        self.hardwareTable.verticalHeader().setSortIndicatorShown(False)
        self.hardwareTable.verticalHeader().setStretchLastSection(True)
        self.label_13 = QtWidgets.QLabel(parent=self.invFrame)
        self.label_13.setGeometry(QtCore.QRect(20, 264, 321, 26))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(22)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_13.setObjectName("label_13")
        self.monitorAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.monitorAdd.setGeometry(QtCore.QRect(760, 333, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.monitorAdd.setFont(font)
        self.monitorAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.monitorAdd.setObjectName("monitorAdd")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.invFrame)
        self.pushButton_2.setGeometry(QtCore.QRect(835, 333, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.kmAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.kmAdd.setGeometry(QtCore.QRect(760, 376, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.kmAdd.setFont(font)
        self.kmAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.kmAdd.setObjectName("kmAdd")
        self.gpuAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.gpuAdd.setGeometry(QtCore.QRect(760, 418, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.gpuAdd.setFont(font)
        self.gpuAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.gpuAdd.setObjectName("gpuAdd")
        self.motherboardAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.motherboardAdd.setGeometry(QtCore.QRect(760, 460, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.motherboardAdd.setFont(font)
        self.motherboardAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.motherboardAdd.setObjectName("motherboardAdd")
        self.ramAdd = QtWidgets.QPushButton(parent=self.invFrame)
        self.ramAdd.setGeometry(QtCore.QRect(760, 502, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.ramAdd.setFont(font)
        self.ramAdd.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;   /* Green color */\n"
"    color: white;                /* Text color */\n"
"    border: 2px solid #4CAF50;  /* Optional border */\n"
"    border-radius: 10px;         /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41;  /* Darker when pressed */\n"
"}")
        self.ramAdd.setObjectName("ramAdd")
        self.kmSub = QtWidgets.QPushButton(parent=self.invFrame)
        self.kmSub.setGeometry(QtCore.QRect(835, 376, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.kmSub.setFont(font)
        self.kmSub.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.kmSub.setObjectName("kmSub")
        self.gpuSub = QtWidgets.QPushButton(parent=self.invFrame)
        self.gpuSub.setGeometry(QtCore.QRect(835, 418, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.gpuSub.setFont(font)
        self.gpuSub.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.gpuSub.setObjectName("gpuSub")
        self.motherboardSub = QtWidgets.QPushButton(parent=self.invFrame)
        self.motherboardSub.setGeometry(QtCore.QRect(835, 460, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.motherboardSub.setFont(font)
        self.motherboardSub.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.motherboardSub.setObjectName("motherboardSub")
        self.ramSub = QtWidgets.QPushButton(parent=self.invFrame)
        self.ramSub.setGeometry(QtCore.QRect(835, 502, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.ramSub.setFont(font)
        self.ramSub.setStyleSheet("QPushButton {\n"
"    background-color: #f44336;   /* Red color */\n"
"    color: white;                 /* Text color */\n"
"    border: 2px solid #f44336;   /* Optional border */\n"
"    border-radius: 10px;          /* Rounded edges */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #da190b;   /* Slightly darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c;   /* Darker when pressed */\n"
"}")
        self.ramSub.setObjectName("ramSub")
        self.createComputerButton = QtWidgets.QPushButton(parent=self.invFrame)
        self.createComputerButton.setGeometry(QtCore.QRect(410, 235, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.createComputerButton.setFont(font)
        self.createComputerButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.createComputerButton.setObjectName("createComputerButton")
        self.currentStatusReportButton = QtWidgets.QPushButton(parent=self.invFrame)
        self.currentStatusReportButton.setGeometry(QtCore.QRect(410, 540, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        self.currentStatusReportButton.setFont(font)
        self.currentStatusReportButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.currentStatusReportButton.setObjectName("currentStatusReportButton")
        self.stackedWidget.addWidget(self.invFrame)
        self.frame.raise_()
        self.stackedWidget.raise_()
        self.menuFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "DAVAO"))
        self.label_4.setText(_translate("MainWindow", "BRANCH"))
        self.label_3.setText(_translate("MainWindow", "Manager: Name"))
        self.logoutButton.setText(_translate("MainWindow", "Log out"))
        self.dashboardButton.setText(_translate("MainWindow", "Dashboard"))
        self.inventoryButton.setText(_translate("MainWindow", "Inventory"))
        self.requestsButton.setText(_translate("MainWindow", "Requests"))
        self.setupsButton.setText(_translate("MainWindow", "Setups"))
        self.registerButton.setText(_translate("MainWindow", "Register"))
        self.label_6.setText(_translate("MainWindow", "2"))
        item = self.assignedComputersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Employee ID"))
        item = self.assignedComputersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee Fullname"))
        item = self.assignedComputersTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pc Number"))
        item = self.assignedComputersTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date Acquired"))
        self.label_5.setText(_translate("MainWindow", "Assigned Computers"))
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.label_9.setText(_translate("MainWindow", "Total Setup Active"))
        self.r1No.setText(_translate("MainWindow", "0"))
        self.r2No.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Total Items/ Activity Log"))
        self.label_12.setText(_translate("MainWindow", "Available PCs"))
        self.r2No_3.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Inventory Level"))
        self.label_11.setText(_translate("MainWindow", "Healthy Stock (Inventory>10)"))
        self.label_16.setText(_translate("MainWindow", "Low Stock (Inventory<10)"))
        self.label_17.setText(_translate("MainWindow", "Critical Stock (Inventory<5)"))
        self.label_18.setText(_translate("MainWindow", "Employee Registration"))
        self.mnlabel.setText(_translate("MainWindow", "Middle Name"))
        self.lnlabel.setText(_translate("MainWindow", "Last Name"))
        self.lnlabel_2.setText(_translate("MainWindow", "Password"))
        self.signUpButton.setText(_translate("MainWindow", "Sign up"))
        self.userLabel.setText(_translate("MainWindow", "First Name"))
        self.userLabel_2.setText(_translate("MainWindow", "Fill out the form below to register a new employee."))
        item = self.issueReportsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PC No."))
        item = self.issueReportsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee ID"))
        item = self.issueReportsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Reason"))
        self.label_14.setText(_translate("MainWindow", "PC Issue Reports"))
        self.selectRequestButton.setText(_translate("MainWindow", "Select Request"))
        self.label_15.setText(_translate("MainWindow", "Request Reports"))
        item = self.requestReportsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PC No."))
        item = self.requestReportsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Requested by"))
        item = self.requestReportsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Hardware Change"))
        item = self.requestReportsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Performed by"))
        item = self.requestReportsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date Started"))
        item = self.requestReportsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date Finished"))
        item = self.requestReportsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Date"))
        item = self.requestReportsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Validator"))
        self.generateReportButton.setText(_translate("MainWindow", "Generate Report"))
        self.showAllBox.setText(_translate("MainWindow", "Show all"))
        item = self.computerSetupsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PC Number"))
        item = self.computerSetupsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Assigned To"))
        item = self.computerSetupsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        self.label_7.setText(_translate("MainWindow", "Computer Setups"))
        item = self.hardwareTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Monitor"))
        item = self.hardwareTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Keyboard & Mouse"))
        item = self.hardwareTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "GPU"))
        item = self.hardwareTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Motherboard"))
        item = self.hardwareTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "RAM"))
        item = self.hardwareTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Brand"))
        item = self.hardwareTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.hardwareTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Add/Remove"))
        __sortingEnabled = self.hardwareTable.isSortingEnabled()
        self.hardwareTable.setSortingEnabled(False)
        item = self.hardwareTable.item(0, 0)
        item.setText(_translate("MainWindow", "Lenovo"))
        item = self.hardwareTable.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.hardwareTable.item(1, 0)
        item.setText(_translate("MainWindow", "Logitech"))
        item = self.hardwareTable.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.hardwareTable.item(2, 0)
        item.setText(_translate("MainWindow", "Nvidia"))
        item = self.hardwareTable.item(2, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.hardwareTable.item(3, 0)
        item.setText(_translate("MainWindow", "ROG"))
        item = self.hardwareTable.item(3, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.hardwareTable.item(4, 0)
        item.setText(_translate("MainWindow", "Kingston"))
        item = self.hardwareTable.item(4, 1)
        item.setText(_translate("MainWindow", "0"))
        self.hardwareTable.setSortingEnabled(__sortingEnabled)
        self.label_13.setText(_translate("MainWindow", "Hardware"))
        self.monitorAdd.setText(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.kmAdd.setText(_translate("MainWindow", "+"))
        self.gpuAdd.setText(_translate("MainWindow", "+"))
        self.motherboardAdd.setText(_translate("MainWindow", "+"))
        self.ramAdd.setText(_translate("MainWindow", "+"))
        self.kmSub.setText(_translate("MainWindow", "-"))
        self.gpuSub.setText(_translate("MainWindow", "-"))
        self.motherboardSub.setText(_translate("MainWindow", "-"))
        self.ramSub.setText(_translate("MainWindow", "-"))
        self.createComputerButton.setText(_translate("MainWindow", "Create New Computer"))
        self.currentStatusReportButton.setText(_translate("MainWindow", "Generate Current Status"))
