# Form implementation generated from reading ui file 'Employeev1.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setTabletTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1101, 121))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(560, 10, 96, 96))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Untitled design (2).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(440, 30, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(670, 30, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(parent=self.frame)
        self.line.setGeometry(QtCore.QRect(170, 115, 891, 10))
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.menuFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.menuFrame.setGeometry(QtCore.QRect(0, 0, 131, 701))
        self.menuFrame.setStyleSheet("QFrame#menuFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius:20px;\n"
"    background-color: rgb(65, 35, 127);\n"
"}\n"
"\n"
"\n"
"")
        self.menuFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.menuEmployeeFrame = QtWidgets.QFrame(parent=self.menuFrame)
        self.menuEmployeeFrame.setGeometry(QtCore.QRect(0, 0, 131, 161))
        self.menuEmployeeFrame.setStyleSheet("QFrame#menuEmployeeFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 20px;\n"
"    \n"
"    background-color: rgb(44, 10, 113);\n"
"}")
        self.menuEmployeeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuEmployeeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuEmployeeFrame.setObjectName("menuEmployeeFrame")
        self.personIcon = QtWidgets.QLabel(parent=self.menuEmployeeFrame)
        self.personIcon.setGeometry(QtCore.QRect(20, 10, 91, 91))
        self.personIcon.setText("")
        self.personIcon.setPixmap(QtGui.QPixmap("person icon.png"))
        self.personIcon.setScaledContents(True)
        self.personIcon.setObjectName("personIcon")
        self.label_3 = QtWidgets.QLabel(parent=self.menuEmployeeFrame)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.menuLogoutFrame = QtWidgets.QFrame(parent=self.menuFrame)
        self.menuLogoutFrame.setGeometry(QtCore.QRect(0, 650, 131, 51))
        self.menuLogoutFrame.setStyleSheet("QFrame#menuLogoutFrame  {\n"
"    background-color: #1e1e1e;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 20px;\n"
"    \n"
"    background-color: rgb(44, 10, 113);\n"
"}")
        self.menuLogoutFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuLogoutFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuLogoutFrame.setObjectName("menuLogoutFrame")
        self.logoutButton = QtWidgets.QPushButton(parent=self.menuLogoutFrame)
        self.logoutButton.setGeometry(QtCore.QRect(10, 10, 101, 24))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"    padding-left: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logoutButton.setIcon(icon)
        self.logoutButton.setIconSize(QtCore.QSize(24, 24))
        self.logoutButton.setCheckable(False)
        self.logoutButton.setObjectName("logoutButton")
        self.reportButton = QtWidgets.QPushButton(parent=self.menuFrame)
        self.reportButton.setGeometry(QtCore.QRect(0, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        self.reportButton.setFont(font)
        self.reportButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: left;\n"
"border: 1.5px solid rgb(44, 10, 113);\n"
"    padding-left: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../IT5 Program/Images/warning.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reportButton.setIcon(icon1)
        self.reportButton.setIconSize(QtCore.QSize(30, 30))
        self.reportButton.setCheckable(False)
        self.reportButton.setObjectName("reportButton")
        self.infoFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.infoFrame.setGeometry(QtCore.QRect(130, 120, 971, 581))
        self.infoFrame.setStyleSheet("QFrame#infoFrame  {\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.infoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.infoFrame.setObjectName("infoFrame")
        self.itemFrame = QtWidgets.QFrame(parent=self.infoFrame)
        self.itemFrame.setGeometry(QtCore.QRect(74, 44, 821, 481))
        self.itemFrame.setStyleSheet("QFrame#itemFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}")
        self.itemFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.itemFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.itemFrame.setObjectName("itemFrame")
        self.pcNoFrame = QtWidgets.QFrame(parent=self.itemFrame)
        self.pcNoFrame.setGeometry(QtCore.QRect(0, 0, 821, 51))
        self.pcNoFrame.setStyleSheet("background-color: rgb(52, 28, 102);\n"
"    border-top-left-radius: 20px;\n"
"       border-top-right-radius: 20px;")
        self.pcNoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pcNoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pcNoFrame.setObjectName("pcNoFrame")
        self.label_5 = QtWidgets.QLabel(parent=self.pcNoFrame)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("pc logo white.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.pcNoFrame)
        self.label_6.setGeometry(QtCore.QRect(60, 10, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.itemFrame)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 361, 371))
        self.label_7.setStyleSheet("border: 1px solid gray;\n"
"    border-radius: 20px;     ")
        self.label_7.setLineWidth(0)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("pc pic (1000 x 1000 px).png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.itemFrame)
        self.label_8.setGeometry(QtCore.QRect(505, 120, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(44, 10, 113);")
        self.label_8.setObjectName("label_8")
        self.itemFrameInside = QtWidgets.QFrame(parent=self.itemFrame)
        self.itemFrameInside.setGeometry(QtCore.QRect(430, 170, 351, 241))
        self.itemFrameInside.setStyleSheet("QFrame#itemFrameInside {\n"
"border: 1px solid gray;\n"
"}")
        self.itemFrameInside.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.itemFrameInside.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.itemFrameInside.setObjectName("itemFrameInside")
        self.line_2 = QtWidgets.QFrame(parent=self.itemFrameInside)
        self.line_2.setGeometry(QtCore.QRect(100, 0, 31, 261))
        self.line_2.setStyleSheet("color: rgb(158, 158, 158);\n"
"color: rgb(129, 129, 129);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_11.setGeometry(QtCore.QRect(40, 120, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_13.setGeometry(QtCore.QRect(40, 200, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.monitorName = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.monitorName.setGeometry(QtCore.QRect(140, 20, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.monitorName.setFont(font)
        self.monitorName.setObjectName("monitorName")
        self.label_14 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_14.setGeometry(QtCore.QRect(140, 70, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_15.setGeometry(QtCore.QRect(140, 120, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_16.setGeometry(QtCore.QRect(140, 160, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.itemFrameInside)
        self.label_17.setGeometry(QtCore.QRect(140, 200, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.notification = QtWidgets.QPushButton(parent=self.infoFrame)
        self.notification.setGeometry(QtCore.QRect(920, 18, 31, 31))
        self.notification.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 25px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgray;  \n"
"    border: 1px solid gray;  \n"
"}")
        self.notification.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../IT5 Program/Images/bell.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.notification.setIcon(icon2)
        self.notification.setIconSize(QtCore.QSize(25, 25))
        self.notification.setObjectName("notification")
        self.infoFrame.raise_()
        self.frame.raise_()
        self.menuFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "DAVAO"))
        self.label_4.setText(_translate("MainWindow", "BRANCH"))
        self.label_3.setText(_translate("MainWindow", "Employee ID: #000"))
        self.logoutButton.setText(_translate("MainWindow", "Log out"))
        self.reportButton.setText(_translate("MainWindow", "Report"))
        self.label_6.setText(_translate("MainWindow", "PC #"))
        self.label_8.setText(_translate("MainWindow", "Specifications"))
        self.label_9.setText(_translate("MainWindow", "Monitor"))
        self.label_10.setText(_translate("MainWindow", "Keyboard & Mouse"))
        self.label_11.setText(_translate("MainWindow", "GPU"))
        self.label_12.setText(_translate("MainWindow", "Motherboard"))
        self.label_13.setText(_translate("MainWindow", "RAM"))
        self.monitorName.setText(_translate("MainWindow", "Lenovo"))
        self.label_14.setText(_translate("MainWindow", "Logitech"))
        self.label_15.setText(_translate("MainWindow", "Nvidia"))
        self.label_16.setText(_translate("MainWindow", "ROG"))
        self.label_17.setText(_translate("MainWindow", "16 GB Kingston"))
