# Form implementation generated from reading ui file 'hardwareChange.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 437)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 361, 171))
        self.frame.setStyleSheet("background-color: rgb(65, 35, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(138, 20, 87, 87))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Untitled design (4).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(25, 110, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(25, 180, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.hardwareComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.hardwareComboBox.setGeometry(QtCore.QRect(20, 250, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hardwareComboBox.setFont(font)
        self.hardwareComboBox.setObjectName("hardwareComboBox")
        self.hardwareComboBox.addItem("")
        self.hardwareComboBox.addItem("")
        self.hardwareComboBox.addItem("")
        self.hardwareComboBox.addItem("")
        self.hardwareComboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.grantBtn = QtWidgets.QPushButton(parent=Dialog)
        self.grantBtn.setGeometry(QtCore.QRect(124, 390, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grantBtn.setFont(font)
        self.grantBtn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.grantBtn.setObjectName("grantBtn")
        self.technicianComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.technicianComboBox.setGeometry(QtCore.QRect(20, 330, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.technicianComboBox.setFont(font)
        self.technicianComboBox.setObjectName("technicianComboBox")
        self.technicianComboBox.addItem("")
        self.technicianComboBox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hardware Change"))
        self.label_2.setText(_translate("Dialog", "Hardware Replacement"))
        self.label_3.setText(_translate("Dialog", "*Please fill out this form for the Hardware Replacement.*"))
        self.label_4.setText(_translate("Dialog", "Hardware"))
        self.hardwareComboBox.setItemText(0, _translate("Dialog", "Monitor"))
        self.hardwareComboBox.setItemText(1, _translate("Dialog", "Keyboard & Mouse"))
        self.hardwareComboBox.setItemText(2, _translate("Dialog", "GPU"))
        self.hardwareComboBox.setItemText(3, _translate("Dialog", "Motherboard"))
        self.hardwareComboBox.setItemText(4, _translate("Dialog", "RAM"))
        self.label_5.setText(_translate("Dialog", "Technician"))
        self.grantBtn.setText(_translate("Dialog", "Grant"))
        self.technicianComboBox.setItemText(0, _translate("Dialog", "Marlo Juan"))
        self.technicianComboBox.setItemText(1, _translate("Dialog", "Levi Alicaya"))
