# Form implementation generated from reading ui file 'itemsAddedv2.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(922, 537)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 931, 121))
        self.frame.setStyleSheet("background-color: rgb(65, 35, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(429, 10, 61, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../IT5 Program/Images/Untitled design (4).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(334, 70, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(60, 169, 801, 321))
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: #41237F;\n"
"    color: white;\n"
"\n"
"}")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(156)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.date1Filter = QtWidgets.QDateEdit(parent=Dialog)
        self.date1Filter.setGeometry(QtCore.QRect(535, 134, 110, 22))
        self.date1Filter.setObjectName("date1Filter")
        self.date2Filter = QtWidgets.QDateEdit(parent=Dialog)
        self.date2Filter.setGeometry(QtCore.QRect(660, 134, 110, 22))
        self.date2Filter.setObjectName("date2Filter")
        self.reportFilterCB = QtWidgets.QComboBox(parent=Dialog)
        self.reportFilterCB.setGeometry(QtCore.QRect(450, 134, 69, 22))
        self.reportFilterCB.setObjectName("reportFilterCB")
        self.reportFilterCB.addItem("")
        self.reportFilterCB.addItem("")
        self.reportFilterCB.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(317, 134, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.applyButton = QtWidgets.QPushButton(parent=Dialog)
        self.applyButton.setGeometry(QtCore.QRect(786, 134, 75, 24))
        self.applyButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.applyButton.setObjectName("applyButton")
        self.generateReportButton = QtWidgets.QPushButton(parent=Dialog)
        self.generateReportButton.setGeometry(QtCore.QRect(405, 501, 111, 24))
        self.generateReportButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.generateReportButton.setObjectName("generateReportButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Items Added Table"))
        self.label_2.setText(_translate("Dialog", "Items Added Table"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hardware Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Adjustment"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Ordered By"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Reason"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Date Added"))
        self.reportFilterCB.setItemText(0, _translate("Dialog", "Weekly"))
        self.reportFilterCB.setItemText(1, _translate("Dialog", "Monthly"))
        self.reportFilterCB.setItemText(2, _translate("Dialog", "Yearly"))
        self.label_3.setText(_translate("Dialog", "Filter by Date Range:"))
        self.applyButton.setText(_translate("Dialog", "Apply"))
        self.generateReportButton.setText(_translate("Dialog", "Generate Report"))
