# Form implementation generated from reading ui file 'ReportFix.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 340)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 321, 171))
        self.frame.setStyleSheet("background-color: rgb(65, 35, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(124, 22, 75, 75))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Untitled design (4).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.checkButton = QtWidgets.QPushButton(parent=Dialog)
        self.checkButton.setGeometry(QtCore.QRect(32, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkButton.setFont(font)
        self.checkButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.checkButton.setObjectName("checkButton")
        self.checkButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.checkButton_2.setGeometry(QtCore.QRect(161, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkButton_2.setFont(font)
        self.checkButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.checkButton_2.setObjectName("checkButton_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(14, 180, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Report"))
        self.label_2.setText(_translate("Dialog", "Problem Action"))
        self.checkButton.setText(_translate("Dialog", "Normal Fix"))
        self.checkButton_2.setText(_translate("Dialog", "Hardware Change"))
        self.label_3.setText(_translate("Dialog", "Note: Select Normal Fix for software issues, configuration changes, or minor adjustments that do not require replacing parts. Choose Hardware Change only when a physical component is faulty or needs replacement."))
