# Form implementation generated from reading ui file 'ReportAction.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 488)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 321, 171))
        self.frame.setStyleSheet("background-color: rgb(65, 35, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(124, 22, 75, 75))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Untitled design (4).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkButton = QtWidgets.QPushButton(parent=Dialog)
        self.checkButton.setGeometry(QtCore.QRect(60, 430, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkButton.setFont(font)
        self.checkButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.checkButton.setObjectName("checkButton")
        self.pcNo = QtWidgets.QLabel(parent=Dialog)
        self.pcNo.setGeometry(QtCore.QRect(150, 192, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(False)
        self.pcNo.setFont(font)
        self.pcNo.setObjectName("pcNo")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 230, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.reqName = QtWidgets.QLabel(parent=Dialog)
        self.reqName.setGeometry(QtCore.QRect(30, 260, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(False)
        self.reqName.setFont(font)
        self.reqName.setObjectName("reqName")
        self.label_9 = QtWidgets.QLabel(parent=Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 290, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.reason = QtWidgets.QLabel(parent=Dialog)
        self.reason.setGeometry(QtCore.QRect(30, 330, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(False)
        self.reason.setFont(font)
        self.reason.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.reason.setWordWrap(True)
        self.reason.setObjectName("reason")
        self.ignoreButton = QtWidgets.QPushButton(parent=Dialog)
        self.ignoreButton.setGeometry(QtCore.QRect(162, 430, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ignoreButton.setFont(font)
        self.ignoreButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ignoreButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(65, 35, 127);\n"
"    border: 2px solid rgb(65, 35, 127);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"}\n"
"")
        self.ignoreButton.setObjectName("ignoreButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Report"))
        self.label_2.setText(_translate("Dialog", "Problem Report"))
        self.label_5.setText(_translate("Dialog", "PC Number:"))
        self.checkButton.setText(_translate("Dialog", "Check"))
        self.pcNo.setText(_translate("Dialog", "1"))
        self.label_8.setText(_translate("Dialog", "Submitted by:"))
        self.reqName.setText(_translate("Dialog", "---------------------------------------"))
        self.label_9.setText(_translate("Dialog", "Reason"))
        self.reason.setText(_translate("Dialog", "---------------------------------------"))
        self.ignoreButton.setText(_translate("Dialog", "Ignore"))
