# Form implementation generated from reading ui file 'stockout.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(382, 255)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 391, 131))
        self.frame.setStyleSheet("background-color: rgb(65, 35, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(160, 18, 61, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Untitled design (4).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 81, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.transferedButton = QtWidgets.QPushButton(parent=Dialog)
        self.transferedButton.setGeometry(QtCore.QRect(60, 202, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.transferedButton.setFont(font)
        self.transferedButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.transferedButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.transferedButton.setObjectName("transferedButton")
        self.checkButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.checkButton_2.setGeometry(QtCore.QRect(200, 202, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkButton_2.setFont(font)
        self.checkButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(65, 35, 127);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 55, 150);\n"
"}")
        self.checkButton_2.setObjectName("checkButton_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(45, 149, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "StockOut"))
        self.label_2.setText(_translate("Dialog", "Stock out Reason"))
        self.transferedButton.setText(_translate("Dialog", "Transfered"))
        self.checkButton_2.setText(_translate("Dialog", "Damaged/Defective"))
        self.label_3.setText(_translate("Dialog", "Kindly choose the appropriate reason for removing this item from inventory."))
